services:

  nginx:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/certs:/etc/ssl/nginx
      - ${PWD}/nginx/logs:/var/log/nginx
      - ${PWD}/nginx/www:/data/www
  objects:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ${PWD}/minio/data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

  chat:
    build: ./chatbot
    environment:
      API_KEY: ${API_KEY}
      API_ENDPOINT: ${API_ENDPOINT}
      MODEL_NAME: ${MODEL_NAME}

  flight:
    build: ./flight_info
    environment:
      API_KEY: ${API_KEY}
      API_ENDPOINT: ${API_ENDPOINT}
      MODEL_NAME: ${MODEL_NAME}
